source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "3.2.2"

gem "rails", "~> 7.0.4", ">= 7.0.4.2"
gem "sprockets-rails"
gem "pg", "~> 1.1"
gem "puma", "~> 5.0"
gem "jsbundling-rails"
gem "cssbundling-rails"
gem "jbuilder"
gem "bootsnap", require: false

# All runtime config comes from the UNIX environment
# but we use dotenv to store that in files for
# development and testing
gem "dotenv-rails", groups: [:development, :test]

# Brakeman analyzes our code for security vulnerabilities
gem "brakeman"

# bundler-audit checks our dependencies for vulnerabilities
gem "bundler-audit"

# Sidekiq uses Redis, but since this app does not have
# Sidekiq installed yet, we bring this gem in so we can connect
# to Redis and validate the reader's setup.
gem "redis"

# This is used to run the dev environment
gem "foreman"

# Prevents our workers from running too long if a request
# doesn't return in time.
gem "rack-timeout"

group :test do
  gem "capybara"
  gem "selenium-webdriver"
  gem "webdrivers"
end
